### ISSUE TITLE
Help running simple example on Google Cloud Platform.

### ISSUE THREAD

**Issue by peterlamar** [SoftwareAG/apama-streaming-analytics-docker-samples#23]
Any help? Do I need Kubernetes running to do docker-compose up on the simple example?
Thanks!
```
docker-compose up
Building application
ERROR: (gcloud.auth.docker-helper) There was a problem refreshing your current auth tokens: invalid_grant: Account has been deleted
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 74, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['/usr/bin/docker-credential-gcloud', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 129, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 87, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-gcloud exited with "".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1080, in up
  File "compose/cli/main.py", line 1076, in up
  File "compose/project.py", line 475, in up
  File "compose/service.py", line 358, in ensure_image_exists
  File "compose/service.py", line 1082, in build
  File "site-packages/docker/api/build.py", line 251, in build
  File "site-packages/docker/api/build.py", line 313, in _set_auth_headers
  File "site-packages/docker/auth.py", line 96, in resolve_authconfig
  File "site-packages/docker/auth.py", line 146, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "".',)
[26331] Failed to execute script docker-compose
```

**Comment by mjj29** [comment]
Hi Peter,

The examples all come with two examples - Docker compose/swarm and Kubernetes. These are separate examples depending on which system you're using. If you have Kubernetes, then don't use docker-compose, instead use kubectl create -f kubernetes.yml. If you re using docker-compose then it's got nothing to do with Kubernetes.

Here it looks like you don't have authentication setup for your gcloud. Have you tried running the recommendation in that error message: gcloud auth login ?

HTH,
Matt

**Comment by peterlamar** [comment]
The issue is why is gcloud auth login being triggered after doing 'docker-compose up'? I fully agree with you, triggering docker-compose should not require Kubernetes but I suspect it may be asking for it. Either way, this is the error I receive after I trigger docker-compose up.

**Comment by mjj29** [comment]
Where is your docker client configured to deploy to?

**Comment by peterlamar** [comment]
A past gcp project. Does running the simple example require a docker registry to deploy to?

**Comment by mjj29** [comment]
If you're deploying to kubernetes yes. If you have a docker server which can do build commands in compose files directly, then no.

**Comment by peterlamar** [comment]
Ok, how would I complete the Simple example using a docker server only? docker-compose up seems to ask for a Kubernetes install

**Comment by mjj29** [comment]
If docker-compose up is asking for a Kubernetes install, it's because you've configured it to use a Kubernetes backend. I've not personally used gcloud, but I suspect that they've providing a Kubernetes API, not a plain docker API.

If you are talking to just a docker server, then docker-compose up is all you need to do.

**Comment by CaribouJohn** [comment]
Ok so my first observation is that there are a billion ways this can be set up on Google resources. Which are you using? E.G. 

https://cloud.google.com/cloud-build/docs/quickstart-docker
https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os

or some other ? Have you set up your project specifically for this example or are you reusing another one that you previously used for a Kubernetes example? I think we need to understand the environment because otherwise there are too many variables

**Comment by peterlamar** [comment]
I am trying to run the example locally, I'll investigate docker-compose default settings

**Comment by peterlamar** [comment]
Sorry for the run around. I found a config file at .docker/config.json that was messing me up. Deleted it and now it works fine :/
Its fairly obscure, but I am happy to add a note to the docs to watch out for this as a tiny part of my penance.

**Comment by CaribouJohn** [comment]
Hi Peter, no problems. Glad you got it working :)
